# This file is auto-generated by the dh-umc tools and should not be edited!
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-quota\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2011-10-23 23:13+0200\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Language: \n"

#: umc/python/quota/tools.py:70
#, python-format
msgid "%s Days"
msgstr "%s Tage"

#: umc/python/quota/user.py:55 umc/python/quota/partition.py:56
#: umc/python/quota/partition.py:87
#, python-format
msgid "Could not open %s"
msgstr "%s konnte nicht geöffnet werden"

#: umc/python/quota/tools.py:135
msgid "Device could not be found"
msgstr "Gerät konnte nicht gefunden werden"

#: umc/python/quota/tools.py:68
msgid "Expired"
msgstr "Abgelaufen"

#: umc/python/quota/user.py:125
#, python-format
msgid "Failed to modify quota settings for user %s on partition %s"
msgstr ""
"Fehler beim Setzen der Quota-Einstellungen für Benutzer %(user)s auf der "
"Partition %(partition)s"

#: umc/python/quota/tools.py:183
msgid "Generating the quota information file failed"
msgstr "Erstellung der Quota-Informationsdatei ist fehlgeschlagen"

#: umc/python/quota/tools.py:167
msgid "Mounting the partition has failed"
msgstr "Einhängen der Partition ist fehlgeschlagen"

#: umc/python/quota/partition.py:103
msgid "No partition found"
msgstr "Keine Partition gefunden"

#: umc/python/quota/user.py:69
#, python-format
msgid "No partition found (%s)"
msgstr "Keine Partition gefunden (%s)"

#: umc/python/quota/tools.py:173 umc/python/quota/tools.py:189
msgid "Operation was successful"
msgstr "Operation war erfolgreich"

#: umc/python/quota/partition.py:118
msgid "Quota support successfully activated"
msgstr "Quota-Unterstützung wurde erfolgreich aktiviert"

#: umc/python/quota/partition.py:134
msgid "Quota support successfully deactivated"
msgstr "Quota-Unterstützung wurde erfolgreich deaktiviert"

#: umc/python/quota/tools.py:178
msgid "Remounting the partition has failed"
msgstr "Erneutes Einhängen der Partition ist fehlgeschlagen"

#: umc/python/quota/tools.py:170 umc/python/quota/tools.py:186
msgid "Restarting the quota services has failed"
msgstr "Neustart des Quota-Dienstes ist fehlgeschlagen"

#: umc/python/quota/user.py:158
msgid "Successfully removed quota settings"
msgstr "Quota-Einstellungen erfolgreich entfernt"

#: umc/python/quota/user.py:129
msgid "Successfully set quota settings"
msgstr "Quota-Einstellungen erfolgreich gesetzt"

#: umc/python/quota/user.py:65
#, python-format
msgid "The following partition is currently not mounted: %s"
msgstr "Die folgende Partition ist momentan nicht eingebunden: %s"

#: umc/python/quota/user.py:61
#, python-format
msgid "The following partition is mounted without quota support: %s"
msgstr "Die folgende Partition ist ohne Quota-Unterstützung eingebunden: %s"

#: umc/python/quota/partition.py:100
msgid "This partition is currently not mounted"
msgstr "Diese Partition is momentan nicht eingebunden"

#: umc/python/quota/tools.py:164
msgid "Unmounting the partition has failed"
msgstr "Aushängen der Partition ist fehlgeschlagen"
