product: ucs
release: "4.4"
version: [1]
scope: ucs_4.4-0-errata4.4-1
src: univention-python
fix: 
desc: |
 This update addresses the following issue(s):
 * Situations where operations are performed during a restart of the
   Open LDAP server will trigger a reconnection in the uldap.py utilities.
bug: [47926]
