# This file is auto-generated by the dh-umc tools and should not be edited!
msgid ""
msgstr ""
"Project-Id-Version: univention-management-console-module-passwordreset\n"
"Report-Msgid-Bugs-To: packages@univention.de\n"
"POT-Creation-Date: 2015-11-04 12:45+0100\n"
"PO-Revision-Date: 2015-09-22 09:23+0200\n"
"Last-Translator: Univention GmbH <packages@univention.de>\n"
"Language-Team: Univention GmbH <packages@univention.de>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: umc/python/passwordreset/sending/send_sms.py:66
msgid "Text Message"
msgstr "SMS"

#: umc/python/passwordreset/sending/send_with_external.py:68
msgid "External"
msgstr "Extern"

#: umc/python/passwordreset/sending/send_email.py:73
msgid "Email"
msgstr "E-Mail"

#: umc/python/passwordreset/__init__.py:122
#: umc/python/passwordreset/__init__.py:135
#: umc/python/passwordreset/__init__.py:202
#: umc/python/passwordreset/__init__.py:224
msgid "User is blacklisted."
msgstr "Benutzer ist auf der schwarzen Liste."

#: umc/python/passwordreset/__init__.py:125
msgid "Successfully changed your contact data."
msgstr "Ihre Kontaktdaten wurden erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:140
msgid "Unknown recovery method '{}'."
msgstr "Unbekannte Wiederherstellungsfunktion '{}'."

#: umc/python/passwordreset/__init__.py:157
msgid "Token for user '{}' still valid. Please retry in one hour."
msgstr ""
"Schlüssel (Token) für Benutzer '{}' ist noch nicht abgelaufen. Bitte später "
"wieder versuchen."

#: umc/python/passwordreset/__init__.py:173
msgid "Successfully send token via {}."
msgstr "Der Schlüssel (Token) wurde erfolgreich mit {} versendet."

#: umc/python/passwordreset/__init__.py:176
msgid ""
"No contact information to send a token for password recovery to has been "
"found."
msgstr ""
"Es wurden keine Kontaktadressen gefunden, an die ein Schlüssel (Token) zur "
"Password Wiederherstellung geschickt werden könnte."

#: umc/python/passwordreset/__init__.py:193
msgid "A problem occurred on the server and has been corrected, please retry."
msgstr ""
"Auf dem Server trat ein Problem auf, das beseitig wurde. Bitte versuchen Sie "
"es erneut."

#: umc/python/passwordreset/__init__.py:206
msgid "Successfully changed your password."
msgstr "Ihr Passwort wurde erfolgreich geändert."

#: umc/python/passwordreset/__init__.py:211
msgid "The token you supplied has expired. Please request a new one."
msgstr ""
"Der Schlüssel (Token) den Sie angegeben haben ist abgelaufen. Bitte fordern "
"Sie einen neuen an."

#: umc/python/passwordreset/__init__.py:215
msgid "The token you supplied could not be found. Please request a new one."
msgstr ""
"Der Schlüssel (Token) den Sie angegeben haben konnte nicht gefunden werden. "
"Bitte fordern Sie einen neuen an."

#: umc/python/passwordreset/__init__.py:222
msgid "Empty username supplied."
msgstr "Leerer Benutzername angegeben."

#: umc/python/passwordreset/__init__.py:227
msgid "No password reset method available for this user."
msgstr ""
"Für diesen Benutzer ist keine Methode zum Passwort zurücksetzen vorhanden."

#: umc/python/passwordreset/__init__.py:261
msgid "Error sending token: {}"
msgstr "Fehler beim Versenden des Schlüssels (Token): {}"

#: umc/python/passwordreset/__init__.py:265
msgid "Error sending token."
msgstr "Fehler beim Versenden des Schlüssels (Token)."

#: umc/python/passwordreset/__init__.py:275
msgid "Username or password is incorrect."
msgstr "Benutzername oder Passwort sind falsch."

#: umc/python/passwordreset/__init__.py:278
msgid "Could not connect to the LDAP server."
msgstr "Konnte keine Verbindung zum LDAP-Server aufbauen."

#: umc/python/passwordreset/__init__.py:294
msgid "Failed to change contact information: {}"
msgstr "Konnte Kontaktdaten nicht ändern: {}"

#: umc/python/passwordreset/__init__.py:305
msgid "The Password has been used already. Please supply a new one."
msgstr "Das Passwort wurde bereits verwendet. Bitte geben Sie ein neues ein."

#: umc/python/passwordreset/__init__.py:339
msgid "Unknown user '{}'."
msgstr "Unbekannter Benutzer '{}'."

#: umc/python/passwordreset/__init__.py:387
msgid ""
"There have been too many requests in the last time. Please wait 5 minutes "
"for the next request."
msgstr ""
"Es gab zu viele Anfragen in der letzten Zeit. Bitte warten Sie 5 Minuten bis "
"zur nächsten Anfrage."

#: umc/python/passwordreset/__init__.py:399
msgid "Program error. Please report this to the administrator."
msgstr "Programm Fehler. Bitte berichten Sie dies dem Administrator."

#: umc/python/passwordreset/send_plugin.py:53
msgid "????"
msgstr "????"
